apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: device-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: device-backend:1.0
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
