apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql
  namespace: device-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mssql
  template:
    metadata:
      labels:
        app: mssql
    spec:
      containers:
      - name: mssql
        image: mcr.microsoft.com/mssql/server:2022-latest

        ports:
        - containerPort: 1433

        env:
        - name: ACCEPT_EULA
          value: "Y"

        - name: MSSQL_SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mssql-secret
              key: SA_PASSWORD

        volumeMounts:
        - mountPath: /var/opt/mssql
          name: mssql-storage

      volumes:
      - name: mssql-storage
        persistentVolumeClaim:
          claimName: mssql-pvc
