apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: device-management
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: device-frontend:1.0
        imagePullPolicy: Never
        ports:
        - containerPort: 4200

        volumeMounts:
          - name: frontend-config
            mountPath: /app/src/assets/config/config.json
            subPath: config.json
          
          - name: frontend-secret
            mountPath: /app/src/assets/secrets/app-name.json
            subPath: app-name.json

      volumes:
        - name: frontend-config
          configMap:
            name: frontend-config

        - name: frontend-secret
          secret:
            secretName: frontend-secret
