apiVersion: v1
kind: Secret
metadata:
  name: frontend-secret
  namespace: device-management
type: Opaque
stringData:
  app-name.json: |
    {
      "applicationName": "Device Management System - Secret"
    }
