---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: frontend-secret
  namespace: device-management
spec:
  encryptedData:
    app-name.json: AgBvZVeqhYtHPL5beCZVw1+Q0Y4HZZfZA/prBgRqi9XzATvcazy5CwPskEWGNHcnm1ocHZ8JvhwuzzJz4WsiS1I1J4AA6kBUrnkTjnjRnJ3r8nhuJtM0tKybri/FH2xQRwE5Btfe/CpwK8e88LnJH3QkcT8YuNkoTQkErAo/ugTVcTqaGHJ+0W+1RYm6JCcGQsFaObj946Tb75KJsMyoTv/GlhoWseyTIzY8ElMCQAlxXKKTTAJJaURMYDKyTP8hs0EWmpdQIW3fA+W6fl1cKkJK25EplailjxfKo5BPE+wDF0dRYoyy6wvwq9Y9S9goXQ7Si3xXsrXkDibkQ/TL78xTn/GNWW8sASfAOaSlVCIDOLGpf70Yc4nwZzdqk9noJOK9WYCcZCnDtKpDk83Gz8ZSTXbQ7I35jIVIgUyGn4xOe62nSZZ8XndXpkym/1qp9lVuDwzTK33XKGNg5sm1IPjoLL71Rr9wPVjlRdWNy2BMGiN2un8TUsfGlfKxkq9IlaWSVuoTWtF9YStKFs95iOedzhXEFDfTIMiXCEg3zARSWNwUmRbVsUYnVJ13y3JZPGPAphWjDVNKvp+U2VOrxsZiktxRtqCQh+OgwwruycXb41SloqKrD6kNEECgShLqKZZub3HzyJIQEXhHwFyTJd365R7lM5IH2u4LT1SdBYGJhhP5hst6tz0co89CqS8nS9f9dKvVpotW8kTR0YQPWdo3N+pulpgkwqdJfo2jwGSjpi+D
  template:
    metadata:
      name: frontend-secret
      namespace: device-management
    type: Opaque
