---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: frontend-secret
  namespace: device-management
spec:
  encryptedData:
    app-name.json: AgCr+cgEkiZwhpvP2dX1KAleKkOUaT77aqF/BYcdEPnjtWDrU8Js4lRbh9dQoem0wh5CNBzaJ+zYZdtolIWgoXEEFCvPsBM4dpabwvd/+oyFQcKZY0L+2fBKERXbKPYuzCv3DQESB4nElTcDxP++SvdjmrdXnFvC3TGQL4u6au4LJwTk97UoT5md7wWLDmNLuEM72VFnNw0ti5eqIDICUGVs4DHiI8GIWpLWf7JpuQd2n8Jf9DgGr/W12YSzWUU5yO+Ima7lKQ99Gt/oqmuSY9vakPgPy+YOYN8DzLQr67aQC5WocuKKRFwq1ulxGV6t4tErYqw7FBuYZRdx8pmXNGVLPQ6kUym5Eh2WwYDuS/j7IoiLL4LBpMc9BgvTuRtHn+h5zVyc7G5E3nXTLZezc/9wRAp+W/Qnuly1hbqxj1GCqL7FQ0GLvsclPAmHWLc4hhTtgu4V+vx7B1oHiQdAmkkdO9z2LzrfeBoYefmveWgMmIMBLWXmv4luucqdfYdOtWiTMQ1CqW+uoEC/bqNNyPytek/sC0x2T7Gten2fNtAOsvx4BqHD36shsr+lqiQAjxVKqoy18DAGW50ceRV+Ca41+aE9ZkUOypfgNHn3nUZuemFklV9qwtWJqfx/vTNvYHrVYJoHUnKySZW2D17Jpq6FlELDDE5oCeZeFYkCPWY7mlp6XioErMm9l3azUQPIFW5rwU74lWtf5mOniTQ58j5Pmu/qBn8Vri45DWGtt+6gCp00KC8cp8c0hduss1JHhW+Dj9wut5zzjhkrVb8Q
  template:
    metadata:
      name: frontend-secret
      namespace: device-management
    type: Opaque
